CODIGO PRA CRIAR O ESBOÇO
boolstatus = Part.Extension.SelectByID2(\"Plano{int(counter)}\", \"PLANE\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchManager.InsertSketch True\n
boolstatus = Part.Extension.selectbyid2(\"Curva{int(counter)}\", \"REFERENCECURVES\", 0, 0, 0, False, 0, Nothing, 0)\n
boolstatus = Part.SketchManager.SketchUseEdge3(False, False)\n




CODIGO PARA FECHAR O ESBOÇO
Set skSegment = Part.SketchManager.CreateLine({lista[x1]}, {lista[x1 + 1]}, {lista[x1 + 2]}, {lista[x1 + 3]}, {lista[x1 + 4]}, {lista[x1 + 5]})\n
Set skSegment = Part.SketchManager.CreateCenterLine(-0.03, -0.05, 0, -0.04, -0.06, 0)\n
Set skPoint = Part.SketchManager.CreatePoint(0, 0, 0)\n\n
boolstatus = Part.Extension.SelectByID2(\"Point1\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n
boolstatus = Part.Extension.SelectByID2(\"Point2\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n
boolstatus = Part.Extension.SelectByID2(\"Point3\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n
boolstatus = Part.Extension.SelectByID2(\"Point4\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n
boolstatus = Part.Extension.SelectByID2(\"Point5\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n
boolstatus = Part.Extension.SelectByID2(\"Point6\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n
boolstatus = Part.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n
boolstatus = Part.Extension.SelectByID2(\"Line2\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n
boolstatus = Part.Extension.SelectByID2(\"Spline2\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchConstraintsDelAll\n\n
boolstatus = Part.Extension.SelectByID2(\"Spline2\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchAddConstraints \"sgFIXED\"\n
boolstatus = Part.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, 0)\n
Part.SketchAddConstraints \"sgFIXED\"\n
boolstatus = Part.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, 0)\n
boolstatus = Part.Extension.SelectByID2(\"Line2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, 0)\n
Part.SketchAddConstraints \"sgPARALLEL\"\n
boolstatus = Part.Extension.SelectByID2(\"Line2\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, 0)\n
boolstatus = Part.Extension.SelectByID2(\"Spline2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, 0)\n
Part.SketchAddConstraints \"sgTANGENT\"\n
boolstatus = Part.Extension.SelectByID2(\"Point6\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
boolstatus = Part.Extension.SelectByID2(\"Line2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, 0)\n
Part.SketchAddConstraints \"sgCOINCIDENT\"\n
boolstatus = Part.Extension.SelectByID2(\"Point6\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
boolstatus = Part.Extension.SelectByID2(\"Spline2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, 0)\n
Part.SketchAddConstraints \"sgCOINCIDENT\"\n
boolstatus = Part.Extension.SelectByID2(\"Point5\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
boolstatus = Part.Extension.SelectByID2(\"Line2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, 0)\n
Part.SketchAddConstraints \"sgCOINCIDENT\"\n
boolstatus = Part.Extension.SelectByID2(\"Point5\", \"SKETCHPOINT\", 0, 0, 0, False, 0, Nothing, 0)\n
boolstatus = Part.Extension.SelectByID2(\"Spline2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, 0)\n
Part.SketchAddConstraints \"sgCOINCIDENT\"\n
Part.SketchManager.InsertSketch True"
                